- name: "Setup icinga repo"
  become: true
  yum:
    name:
      - "epel-release"
      - "centos-release-scl"
      - "https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm"

- name: "Install packages"
  become: true
  yum:
    name:
      - "git"
      - "httpd"
      - "icingaweb2"
      - "icingaweb2-selinux"
      - "rh-php71-php-devel"
      - "rh-php71-php-fpm"
      - "rh-php71-php-gd"
      - "rh-php71-php-intl"
      - "rh-php71-php-ldap"
      - "rh-php71-php-mysqlnd"
      - "rh-php71-php-pdo"
      - "rh-php71-php-pear"
      - "rh-php71-php-xml"

- name: "Install icingaweb2 Dependencies"
  become: true
  shell: |
    git clone https://github.com/Icinga/icingaweb2-module-{{ item.name }} "/usr/share/icingaweb2/modules/{{ item.name }}" --branch "{{ item.version }}"
    icingacli module enable "{{ item.name }}"
  loop: "{{ icinga2_web.modules }}"

- name: "Fix /etc/icingaweb2 permissions"
  become: true
  file:
    dest: "/etc/icingaweb2"
    mode: "770"

- name: "Add apache user to icingaweb2 group"
  become: true
  user:
    name: "apache"
    groups: "icingaweb2"
    append: "yes"

- name: "Install httpd.conf"
  become: true
  template:
    src: "httpd.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"
  vars:
    httpd: "{{ icinga2_web.httpd }}"

- name: "Enable and start httpd"
  become: true
  systemd:
    name: "httpd"
    state: "restarted"
    enabled: "yes"

- name: "Start & enable rh-php71-php-fpm"
  become: true
  systemd:
    name: "rh-php71-php-fpm"
    state: "restarted"
    enabled: "yes"

#- name: "Check if firewalld installed"
#  become: true
#  command: "systemctl status firewalld"
#  register: firewalld_result
#  ignore_errors: true
#
#- name: "Open firewall for httpd"
#  become: true
#  firewalld:
#    port: "{{ icinga2_web.httpd.port | default('80') }}/tcp"
#    permanent: "yes"
#    immediate: "yes"
#    state: "enabled"
#  when: firewalld_result.rc == 0

- name: "Setup config directory"
  become: true
  shell: "icingacli setup config directory --group icingaweb2;"

- name: "Get setup token"
  become: true
  shell: "icingacli setup token create"
  register: "token"

- debug: msg="setup token is \"{{ token }}\""
